[package]
name = "insync"
version = "0.1.0"
authors = ["Imani Dap <imani.dap@gmail.com>"]
edition = "2018"

[dependencies]
three = "0.4.0"
recs = "2.0.1"
rand = "0.6.5"
mint = "0.5.1"
clokwerk = "0.1.0"